maykinmedia/charts

charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/values.yaml

Readme values

---

README.md
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/templates/_helpers.tpl
charts/objecttypen/templates/configmap.yaml
charts/objecttypen/templates/deployment.yaml
charts/objecttypen/templates/hpa.yaml
charts/objecttypen/templates/ingress.yaml
charts/objecttypen/templates/secret.yaml
charts/objecttypen/templates/service.yaml
charts/objecttypen/templates/serviceaccount.yaml
charts/objecttypen/values.yaml

Rename openobjectypes to objecttypen

---

charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/templates/configmap.yaml
charts/openzaak/templates/ingress.yaml
charts/openzaak/templates/pdb.yaml
charts/openzaak/templates/serviceaccount.yaml
charts/openzaak/values.yaml

- Remove spaces in allowed_hosts configmap
- add pdb
- add extra ingresses
- add automountServiceAccountToken to serviceaccount

:hammer: openzaak same features as objecten

---

charts/openzaak/Chart.yaml
charts/openzaak/templates/configmap-nginx.yaml
charts/openzaak/templates/configmap.yaml

Add service port number to proxy_pass

:bricks: nginx config

---

charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/templates/configmap-nginx.yaml
charts/openinwoner/templates/configmap.yaml

- ES_HOST aangepast, deze moet verwijzen naar de coordinating service;
- Nginx config add http host header (CSRF erros admin login nu) (https://github.com/maykinmedia/charts/pull/12/files)

:wrench: es host fix

---

charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/templates/configmap-nginx.yaml
charts/openforms/values.yaml

Partly Fixes https://github.com/open-formulieren/open-forms/issues/3421

Increase the max size of allowed form import

---

charts/openforms/Chart.yaml
charts/openforms/templates/configmap.yaml
charts/openforms/values.yaml

@sjoerdie Maybe we should also bump the app version in the Chart.yaml?

Add escape registration setting

---

charts/opennotificaties/Chart.yaml
charts/opennotificaties/templates/configmap.yaml
charts/opennotificaties/templates/deployment.yaml
charts/opennotificaties/templates/pvc.yaml
charts/opennotificaties/values.yaml

- Persist `/app/media` to facilitate OAS file upload;
- Notification delivery settings in values.yml;

Persist /app/media

---

charts/opennotificaties/templates/configmap.yaml
charts/opennotificaties/templates/cronjob-config.yaml
charts/opennotificaties/templates/deployment.yaml
charts/opennotificaties/templates/secret.yaml
charts/opennotificaties/values.yaml
charts/openzaak/templates/configmap.yaml
charts/openzaak/templates/cronjob-config.yaml
charts/openzaak/templates/deployment.yaml
charts/openzaak/templates/secret.yaml
charts/openzaak/values.yaml

Add setup_configuration.sh init containers.

:tada: setup_configuration init containers

---

charts/openforms/Chart.yaml
charts/openforms/values.yaml

Enable celery worker probe by default.

:bookmark: Release 2.3.0

---

charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/templates/_helpers.tpl
charts/openinwoner/templates/configmap.yaml
charts/openinwoner/templates/deployment.yaml
charts/openinwoner/templates/secret.yaml
charts/openinwoner/values.yaml

- :sparkles: Add Celery Beat container
- :sparkles: Add Celery Monitor container
- :fire: Remove load-fixtures
- :stethoscope: Celery health check enabled
**environment variables:**
- `ACCOUNTS_SMS_GATEWAY_BACKEND` & `ACCOUNTS_SMS_GATEWAY_API_KEY`
- `BRP_VERSION`
- `EHERKENNING_MOCK`
- :fire: `TWO_FACTOR_FORCE_OTP_ADMIN` & `TWO_FACTOR_PATCH_ADMIN`

Feature/openinwoner release 1.5.0

---

charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/templates/configmap-nginx.yaml
charts/openarchiefbeheer/templates/configmap.yaml
charts/openarchiefbeheer/templates/deployment.yaml
charts/openarchiefbeheer/templates/service.yaml
charts/openarchiefbeheer/values.yaml

Deployed on our k8 cluster :rocket:

Add frontend URL setting

---

.gitignore
charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/templates/configmap.yaml
charts/openinwoner/values.yaml

🎉 Openinwoner helm release 1.5.1
📝 Update README.MD
🩺 Significantly increase worker livenessProbe periodSeconds and failureThreshold to prevent unintentional killing of worker pod
🧱 Enable ElasticSearch persistence by default

:bookmark: openinwoner helm release version 1.5.1

---

charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/templates/configmap.yaml
charts/objecten/values.yaml
charts/objecttypen/Chart.lock
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/templates/configmap.yaml
charts/objecttypen/values.yaml
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/templates/configmap.yaml
charts/opennotificaties/values.yaml
charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/templates/configmap.yaml
charts/openzaak/values.yaml

Objecten, objecttypes, openzaak, opennotificaties:
- Global database host.
- Disable 2fa
- :stethoscope: objecten increase health check failureThreshold

Multiple helm releases

---

charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/values.yaml
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/values.yaml
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/values.yaml
charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/values.yaml
charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/values.yaml
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/values.yaml
charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/values.yaml
charts/openzaaktypebeheer/Chart.yaml
charts/openzaaktypebeheer/README.md
charts/openzaaktypebeheer/values.yaml

:bricks: Enable redis persistence for all

---

charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/values.yaml
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/values.yaml

Add defaultfrom value to values

Add defaultfrom to objecten 2.4.3 / objecttypen 1.1.3

---

charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/templates/deployment.yaml
charts/openzaak/values.yaml

- Add beat pod
- No more opt out of celery
- Default flower deploy to false (its utterly useless)

:bookmark: Openzaak chart 1.5.0 - add celery beat

---

charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/templates/deployment.yaml
charts/opennotificaties/values.yaml

- add beat deploy
- default flower deploy to false, its useless.

:bookmark: opennotificaties 1.5.0 - add beat

---

charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/templates/configmap.yaml

Remove the  `{{- if .Values.settings.celery.enabled }}` statements from configmap.

:ambulance: openzaak celery envvars fix

---

charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/templates/configmap.yaml
charts/openklant/values.yaml
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/values.yaml
charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/values.yaml

Add defaultfrom email to all components.

Add defaultFrom to values

---

charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/templates/basic-auth-nginx.yaml
charts/openinwoner/templates/configmap-nginx.yaml
charts/openinwoner/templates/deployment.yaml
charts/openinwoner/values.yaml

- Add nginx basic authentication future for edge cases where you cannot enable this through your own nginx controller

Support oip basic authenticaton through nginx pod

---

charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/templates/_helpers.tpl
charts/objecten/templates/configmap.yaml
charts/objecten/templates/deployment.yaml
charts/objecten/templates/job-config.yaml
charts/objecten/templates/secret.yaml
charts/objecten/values.yaml

Add `./src/manage.py setup configuration` init container, job and envvars

:bookmark: objecten release 2.5.0 add setup configuration

---

charts/registratie-component/Chart.lock
charts/registratie-component/Chart.yaml
charts/registratie-component/README.md
charts/registratie-component/templates/_helpers.tpl
charts/registratie-component/templates/azurekeyvaultsecrets.yaml
charts/registratie-component/templates/configmap-nginx.yaml
charts/registratie-component/templates/configmap.yaml
charts/registratie-component/templates/deployment.yaml
charts/registratie-component/templates/hpa.yaml
charts/registratie-component/templates/ingress.yaml
charts/registratie-component/templates/pdb.yaml
charts/registratie-component/templates/pvc.yaml
charts/registratie-component/templates/secret.yaml
charts/registratie-component/templates/service.yaml
charts/registratie-component/templates/serviceaccount.yaml
charts/registratie-component/values.yaml

Fixes https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/107 (partially)

Registratie component helm chart

---

README.md
charts/icatt-odpc/.helmignore
charts/icatt-odpc/Chart.lock
charts/icatt-odpc/Chart.yaml
charts/icatt-odpc/README.md
charts/icatt-odpc/templates/_helpers.tpl
charts/icatt-odpc/templates/configmap.yaml
charts/icatt-odpc/templates/deployment.yaml
charts/icatt-odpc/templates/hpa.yaml
charts/icatt-odpc/templates/ingress.yaml
charts/icatt-odpc/templates/pdb.yaml
charts/icatt-odpc/templates/secret.yaml
charts/icatt-odpc/templates/service.yaml
charts/icatt-odpc/templates/serviceaccount.yaml
charts/icatt-odpc/values.yaml

Partially fixes https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/107
Todo: 
- Figure out if it really doesn't need volumes

ODPC chart

---

charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/templates/deployment.yaml
charts/openarchiefbeheer/values.yaml

[#119] Disabling liveness probes

---

charts/opennotificaties/CHANGELOG.md
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/templates/pdb.yaml
charts/opennotificaties/values.yaml

Fixes #150 
At city Den Haag we would like to use a poddisruptionbudget for ON workers.

Add pdb for worker

---

.github/workflows/ci.yaml
charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.lock
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md
charts/openarchiefbeheer/templates/celery-liveness-configmap.yaml
charts/openarchiefbeheer/templates/configmap-celery.yaml
charts/openarchiefbeheer/templates/deployment.yaml
charts/openarchiefbeheer/values.yaml

[#165] Support different queue/worker names in probe OAB

---

charts/opennotificaties/CHANGELOG.md
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/templates/hpa.yaml
charts/opennotificaties/values.yaml

At city Den Haag we want to control the behavior of the hpa.
Fixes: #149

Add autoscaling behavior for ON

---

charts/opennotificaties/CHANGELOG.md
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/templates/configmap.yaml
charts/opennotificaties/templates/configuration-secrets.yaml
charts/opennotificaties/templates/job-config.yaml
charts/opennotificaties/templates/secret.yaml
charts/opennotificaties/values.yaml

Part of https://github.com/maykinmedia/charts/issues/174

:bookmark: Stable release for Open notificaties

---

charts/openforms/CHANGELOG.md
charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/templates/configuration-secrets.yaml
charts/openforms/templates/job-config.yaml
charts/openforms/values.yaml

:bookmark: Stable release for OpenForms

---

charts/objecten/CHANGELOG.md
charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/templates/configmap.yaml
charts/objecten/templates/configuration-secrets.yaml
charts/objecten/templates/job-config.yaml
charts/objecten/templates/secret.yaml
charts/objecten/values.yaml

:bookmark: Stable release for objecten

---

charts/openinwoner/CHANGELOG.md
charts/openinwoner/Chart.yaml
charts/openinwoner/templates/configmap.yaml
charts/openinwoner/values.yaml

OIP Counterpart: https://github.com/maykinmedia/open-inwoner/pull/1599

Bring OIP uWSGI settings in sync with v1.27.0

---

charts/objecttypen/CHANGELOG.md
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/templates/configmap.yaml
charts/objecttypen/templates/configuration-secrets.yaml
charts/objecttypen/templates/job-config.yaml
charts/objecttypen/templates/secret.yaml
charts/objecttypen/values.yaml

:bookmark: Stable release for objecttypen

---

charts/openklant/CHANGELOG.md
charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/templates/configuration-secrets.yaml
charts/openklant/templates/job-config.yaml
charts/openklant/values.yaml

Part of https://github.com/maykinmedia/charts/issues/174

:bookmark: Stable release for Open Klant

---

charts/openinwoner/CHANGELOG.md
charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/templates/configuration-secrets.yaml
charts/openinwoner/templates/job-config.yaml
charts/openinwoner/values.yaml

Part of https://github.com/maykinmedia/charts/issues/174

:bookmark: Stable release for Open Inwoner

---

charts/openzaak/CHANGELOG.md
charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/templates/configmap.yaml
charts/openzaak/templates/configuration-data.yaml
charts/openzaak/templates/configuration-secrets.yaml
charts/openzaak/templates/job-config.yaml
charts/openzaak/values.yaml

:bookmark: Stable release Open-Zaak

---

charts/objecten/CHANGELOG.md
charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/values.yaml
charts/objecttypen/CHANGELOG.md
charts/objecttypen/Chart.yaml
charts/objecttypen/README.md
charts/objecttypen/values.yaml
charts/openforms/CHANGELOG.md
charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/values.yaml
charts/openinwoner/CHANGELOG.md
charts/openinwoner/Chart.yaml
charts/openinwoner/README.md
charts/openinwoner/values.yaml
charts/openklant/CHANGELOG.md
charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/values.yaml
charts/opennotificaties/CHANGELOG.md
charts/opennotificaties/Chart.yaml
charts/opennotificaties/README.md
charts/opennotificaties/values.yaml
charts/openzaak/CHANGELOG.md
charts/openzaak/Chart.yaml
charts/openzaak/README.md
charts/openzaak/values.yaml

[#197] Increase charts default values

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md
charts/openarchiefbeheer/templates/configmap.yaml
charts/openarchiefbeheer/values.yaml

Fixes maykinmedia/open-archiefbeheer#738
Hesitating a bit about the semver. This is technically a breaking change, but the app 1.0.0 is not released yet, so it feels odd to number the chart 2.0.0 :thinking: 
@svenvandescheur fyi

[maykinmedia/open-archiefbeheer#738] Update env vars

---

README.md

At some point it would be good to somewhat automate the process, but for now this is a checklist.

Document contribution process

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.lock
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md

:bug: [#193] Added missing dependency to Bitnami commons

---

charts/openklant/CHANGELOG.md
charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/templates/extra-deploy.yaml
charts/openklant/values.yaml

Added the extraDeploy as asked by the issue:
Fixes https://github.com/maykinmedia/charts/issues/201

Adding extraDeploy to OpenKlant

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md
charts/openarchiefbeheer/templates/configmap.yaml
charts/openarchiefbeheer/values.yaml

https://github.com/maykinmedia/open-archiefbeheer/issues/800

Add configuration cache

---

charts/openforms/CHANGELOG.md
charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/templates/tls-secret.yaml
charts/openforms/values.yaml

This is just for the Openforms. 
I will add the same for the rest of the applications.

Adding tls secret for openforms chart

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md

[#210] Pin OAB app version to 1.0.0

---

charts/openproduct/.helmignore
charts/openproduct/CHANGELOG.md
charts/openproduct/Chart.lock
charts/openproduct/Chart.yaml
charts/openproduct/README.md
charts/openproduct/templates/_helpers.tpl
charts/openproduct/templates/azurekeyvaultsecrets.yaml
charts/openproduct/templates/celery-liveness-configmap.yaml
charts/openproduct/templates/configmap-celery.yaml
charts/openproduct/templates/configmap.yaml
charts/openproduct/templates/configuration-data.yaml
charts/openproduct/templates/configuration-secrets.yaml
charts/openproduct/templates/deployment.yaml
charts/openproduct/templates/hpa.yaml
charts/openproduct/templates/ingress.yaml
charts/openproduct/templates/job-config.yaml
charts/openproduct/templates/pdb.yaml
charts/openproduct/templates/pvc.yaml
charts/openproduct/templates/secret.yaml
charts/openproduct/templates/service.yaml
charts/openproduct/templates/serviceaccount.yaml
charts/openproduct/values.yaml

https://github.com/maykinmedia/open-product/issues/101
All library charts from maykin-utils-lib used here.

Initial commit Openproduct app helm chart

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md
charts/openarchiefbeheer/templates/configmap.yaml
charts/openarchiefbeheer/values.yaml

[#222] Remove unused env vars in OAB

---

charts/openforms/CHANGELOG.md
charts/openforms/Chart.yaml
charts/openforms/README.md
charts/openforms/templates/deployment.yaml
charts/openforms/values.yaml

Openforms -> remove initContainer used for setup configuration

---

charts/objecten/CHANGELOG.md
charts/objecten/Chart.yaml
charts/objecten/README.md
charts/objecten/templates/configmap.yaml
charts/objecten/values.yaml

Fixes maykinmedia/objects-api#643

:wrench: [maykinmedia/objects-api#643] Expose Celery result_expires

---

charts/openklant/CHANGELOG.md
charts/openklant/Chart.yaml
charts/openklant/README.md
charts/openklant/templates/deployment.yaml
charts/openklant/templates/hpa.yaml

https://github.com/maykinmedia/charts/issues/284

Openklant: fixing worker replicas and HPA

---

charts/openarchiefbeheer/CHANGELOG.md
charts/openarchiefbeheer/Chart.yaml
charts/openarchiefbeheer/README.md
charts/openarchiefbeheer/templates/configmap.yaml
charts/openarchiefbeheer/values.yaml

Fixes https://github.com/maykinmedia/open-archiefbeheer/issues/857

Add variables for logging OAB
