- charts/openforms/Chart.yaml
- charts/openforms/templates/_helpers.tpl
Because some organisations like to run the same application twice with different names in the same namespace................... :see_no_evil:
> use fullname for selectorlabels

- charts/opennotificaties/Chart.yaml
- charts/opennotificaties/values.yaml
By default  bitname/rabbitmq subchart tries to create rbac roles, requiring cluster admin permissions. 
Disable rbac create:
```
rbac.create: false
```
Clustering needs to be disabled when not using rbac or else the rabbitmq pod will fail.
```
clustering.enabled: false
```
> Disable rabbitmq clustering by default

- charts/openforms/Chart.yaml
- charts/openforms/templates/configmap-nginx.yaml
- charts/openforms/values.yaml
Requested by Gemeente Utrecht.
Set Access-Control-Allow-Origin ```CORS_ALLOWED_HOSTS``` in nginx config.
Update static Set Access-Control-Allow-Origin according to openformulieren [readthedocs](https://open-forms.readthedocs.io/en/latest/developers/sdk/embedding.html?highlight=CORS#cross-origin-resource-sharing-cors)
> Openforms cors nginx

- charts/openinwoner/Chart.yaml
OIP AKS testomgeving draait zo te zien nog op een verouderde versie, poging van mijn kant om dit naar 1.7 te upgraden
> Updating to latest version of OIP

- charts/openinwoner/Chart.yaml
- charts/openinwoner/templates/configmap-nginx.yaml
- charts/openinwoner/values.yaml
- nginx config, proxy_headers to fix CSRF error when trying to log in to the /admin;
- Switch private_media to media;
- Update `appVersion` + `appVersion`; 
Tested, works.
> Fix openinwoner nginx config to work with new version of openinwoner

- charts/objecten/Chart.yaml
- charts/objecten/README.md
- charts/objecten/templates/_helpers.tpl
- charts/objecten/templates/configmap-nginx.yaml
- charts/objecten/templates/deployment.yaml
- charts/objecten/templates/ingress.yaml
- charts/objecten/templates/pvc.yaml
- charts/objecten/templates/service.yaml
- charts/objecten/values.yaml
zgw-consumers 2.0 allows OAS file uploads that are place on `/app/media`, so this needs a persistent volume.
Nginx pod so you can click the file without a 404.
> :sparkles: Objecten 2.2.1 support oas file uploads

- charts/openinwoner/Chart.yaml
- charts/openinwoner/templates/configmap-nginx.yaml
Taiga dimpact 68
Django applications listen to HTTP_X_FORWARDED_PROTO if provided, otherwise Django falls back on 'https' by default.
nginx however now uses $scheme which in the chart is http instead of https, as such Django things it's not behind https.
Removing this line ensures openinwoner works the same as openformulieren, making use of the 'https' default
> Modify openinwoner configmap-nginx to use https for x-forwarded-proto

- charts/openforms/Chart.yaml
- charts/openforms/README.md
- charts/openforms/templates/azurekeyvaultsecrets.yaml
- charts/openforms/templates/configmap.yaml
- charts/openforms/values.yaml
:tada: Openforms helm release 1.4.0
- :memo: Update `README.MD`
- :stethoscope: Significantly increase worker livenessProbe `periodSeconds` and `failureThreshold` to prevent unintentional killing of worker pod
- :arrow_up: Default celery worker replicas set to 2
- :bricks:  Enable redis persistence by default
> :bookmark: Release openforms chart version 1.4.0

- charts/openforms/Chart.yaml
- charts/openforms/README.md
- charts/openforms/templates/clean-script.yaml
- charts/openforms/templates/cronjob-clean-logs.yaml
- charts/openforms/values.yaml
Add clean logs script (Message and TimelineLog) and cronjob to clean logs in openforms.
```
~$ k get pods
NAME                                  READY   STATUS      RESTARTS      AGE
openforms-776fc4f678-5cbll            1/1     Running     2 (24m ago)   31m
openforms-beat-76ff6c95f6-g6vjz       1/1     Running     0             31m
openforms-clean-logs-28796274-r4pb6   0/1     Completed   0             34s
openforms-flower-5dfc448d7f-msbz4     1/1     Running     0             31m
openforms-nginx-b756d8f45-bgmtr       1/1     Running     0             31m
openforms-redis-master-0              1/1     Running     0             31m
openforms-worker-75f7c6cc59-7h8mm     1/1     Running     0             31m
openforms-worker-75f7c6cc59-zlt8c     1/1     Running     0             31m
(ansible) …
```
> Add cronjob to clean openforms logs

- charts/openforms/Chart.yaml
- charts/openforms/README.md
- charts/openforms/templates/configmap.yaml
- charts/openforms/values.yaml
- Support new `SHOW_ENVIRONMENT` label environment variables. By default these will NOT be enabled, overriding application defaults. See https://open-forms.readthedocs.io/en/latest/installation/config.html#other-settings for more information.
- :fire: remove unused beat values (it has no health probes, nor can it be disabled)
Note, this chart will work with older openforms versions (e.g 7.x), the new environment variables will take no effect.
> :bookmark: Openforms helm 1.5.0

- charts/openinwoner/Chart.yaml
- charts/openinwoner/README.md
- charts/openinwoner/templates/deployment.yaml
- charts/openinwoner/values.yaml
Feature to run `/app/src/manage.py search_index --rebuild -f` with an init container. This command is run with celery during night time. So new deployments will not have the Elasticsearch indexes and the search feature will cause an 500 error.
Running the initcontainer on new deployments will prevent this.
> search_index --rebuild  init container

- charts/objecten/Chart.yaml
- charts/objecten/values.yaml
Typo in values configuration `enable` -> `enabled` and do not use job by default.
> Objecten 2.5.1 - :pencil2: values

- .github/workflows/ci.yaml
- .github/workflows/release.yml
> [#63] Add lint to CI

- charts/openinwoner/Chart.yaml
- charts/openinwoner/README.md
- charts/openinwoner/templates/configmap.yaml
- charts/openinwoner/values.yaml
Fixes #162
The variables `UWSGI_PROCESSES` and `UWSGI_THREADS` were already present, so I only added `UWSGI_PORT` and `UWSGI_HTTP_TIMEOUT`.
> [#162] Add uwsgi vars OIP

- charts/maykin-utils-lib/.helmignore
- charts/maykin-utils-lib/Chart.yaml
- charts/maykin-utils-lib/templates/_celery-configmap.tpl
- charts/maykin-utils-lib/templates/_celery-liveness-configmap.tpl
- charts/maykin-utils-lib/templates/_helpers.tpl
Part of #165 
Started adding a helm library chart for shared code between charts.
> :sparkles: Added helm library chart

- charts/maykin-utils-lib/CHANGELOG.md
- charts/maykin-utils-lib/Chart.yaml
- charts/maykin-utils-lib/templates/_celery-configmap.tpl
- charts/maykin-utils-lib/templates/_celery-liveness-configmap.tpl
- charts/maykin-utils-lib/templates/_helpers.tpl
- charts/maykin-utils-lib/templates/_nginx-hpa.tpl
- charts/maykin-utils-lib/templates/_webapp-hpa.tpl
- charts/maykin-utils-lib/templates/_worker-hpa.tpl
- charts/objecten/CHANGELOG.md
- charts/objecten/Chart.yaml
- charts/objecten/README.md
- charts/objecten/templates/deployment.yaml
- charts/objecten/templates/hpa.yaml
- charts/objecten/values.yaml
- charts/openzaak/CHANGELOG.md
- charts/openzaak/Chart.yaml
- charts/openzaak/README.md
- charts/openzaak/templates/deployment.yaml
- charts/openzaak/templates/hpa.yaml
> [#172] Update HPA

- charts/openklant/CHANGELOG.md
- charts/openklant/Chart.yaml
- charts/openklant/README.md
- charts/openklant/templates/_helpers.tpl
- charts/openklant/templates/configmap-nginx.yaml
- charts/openklant/templates/deployment.yaml
- charts/openklant/templates/hpa.yaml
- charts/openklant/templates/ingress.yaml
- charts/openklant/templates/persistent-volume-claim.yaml
- charts/openklant/templates/service.yaml
- charts/openklant/values.yaml
Fixes https://github.com/maykinmedia/open-klant/issues/299
> [maykinmedia/open-klant#299] Add nginx Open Klant charts

- charts/maykin-utils-lib/CHANGELOG.md
- charts/maykin-utils-lib/Chart.yaml
- charts/maykin-utils-lib/templates/_helpers.tpl
* Small correction/addition. 
The project.chart is used in project.lables which is used in the current hpa libraries.
> Adding project.chart label, referenced in project.labels

- charts/opennotificaties/CHANGELOG.md
- charts/opennotificaties/Chart.yaml
- charts/opennotificaties/README.md
- charts/opennotificaties/templates/configmap.yaml
- charts/opennotificaties/values.yaml
Fixes  [open-zaak/open-notificaties#240]
Related open-notificaties PR https://github.com/open-zaak/open-notificaties/pull/266
> :sparkles: [open-zaak/open-notificaties#240] Expose `result_expires` Celery setting via envvar

- charts/opennotificaties/CHANGELOG.md
- charts/opennotificaties/Chart.yaml
- charts/opennotificaties/README.md
- charts/opennotificaties/templates/configmap.yaml
- charts/opennotificaties/values.yaml
Source for the env variable documentation.
https://github.com/open-zaak/open-notificaties/blob/1a393b0184a3e20741af769b906e1a95f122831d/docs/installation/configuration/env_config.rst#L51
Variable added in response to Podiumd issue IN-901, so  that more logging can be provided.
> Adding new env variable logLevel

- charts/openinwoner/CHANGELOG.md
- charts/openinwoner/Chart.lock
- charts/openinwoner/Chart.yaml
- charts/openinwoner/README.md
- charts/openinwoner/values.yaml
Here we upgrade to the latest Bitnami charts before the change of the policy.
For the Redis chart the official Redis image is pinned, which appears to work correctly.
The Bitnami image is pinned for the Elasticsearch sub-chart. 
linked to the another PR which can be closed  -> https://github.com/maykinmedia/charts/pull/248
https://github.com/maykinmedia/charts/issues/247
> Openinwoner upgrade bitnami charts Redis and Common 
